/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessGrantOrganization
 */
export interface AccessGrantOrganization {
    /**
     * 
     * @type {string}
     * @memberof AccessGrantOrganization
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AccessGrantOrganization
     */
    serialNumber?: string;
}

export function AccessGrantOrganizationFromJSON(json: any): AccessGrantOrganization {
    return AccessGrantOrganizationFromJSONTyped(json, false);
}

export function AccessGrantOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessGrantOrganization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'serialNumber': !exists(json, 'serialNumber') ? undefined : json['serialNumber'],
    };
}

export function AccessGrantOrganizationToJSON(value?: AccessGrantOrganization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'serialNumber': value.serialNumber,
    };
}


