/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ManagementOrganization,
    ManagementOrganizationFromJSON,
    ManagementOrganizationFromJSONTyped,
    ManagementOrganizationToJSON,
} from './ManagementOrganization';

/**
 * 
 * @export
 * @interface DirectoryListParticipantsResponseDirectoryParticipant
 */
export interface DirectoryListParticipantsResponseDirectoryParticipant {
    /**
     * 
     * @type {ManagementOrganization}
     * @memberof DirectoryListParticipantsResponseDirectoryParticipant
     */
    organization?: ManagementOrganization;
}

export function DirectoryListParticipantsResponseDirectoryParticipantFromJSON(json: any): DirectoryListParticipantsResponseDirectoryParticipant {
    return DirectoryListParticipantsResponseDirectoryParticipantFromJSONTyped(json, false);
}

export function DirectoryListParticipantsResponseDirectoryParticipantFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectoryListParticipantsResponseDirectoryParticipant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organization': !exists(json, 'organization') ? undefined : ManagementOrganizationFromJSON(json['organization']),
    };
}

export function DirectoryListParticipantsResponseDirectoryParticipantToJSON(value?: DirectoryListParticipantsResponseDirectoryParticipant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organization': ManagementOrganizationToJSON(value.organization),
    };
}

