/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ExternalOrganization } from './ExternalOrganization';
import {
    ExternalOrganizationFromJSON,
    ExternalOrganizationFromJSONTyped,
    ExternalOrganizationToJSON,
} from './ExternalOrganization';
import type { ManagementexternalOrderService } from './ManagementexternalOrderService';
import {
    ManagementexternalOrderServiceFromJSON,
    ManagementexternalOrderServiceFromJSONTyped,
    ManagementexternalOrderServiceToJSON,
} from './ManagementexternalOrderService';

/**
 * 
 * @export
 * @interface ExternalIncomingOrder
 */
export interface ExternalIncomingOrder {
    /**
     * 
     * @type {string}
     * @memberof ExternalIncomingOrder
     */
    reference?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalIncomingOrder
     */
    description?: string;
    /**
     * 
     * @type {ExternalOrganization}
     * @memberof ExternalIncomingOrder
     */
    delegator?: ExternalOrganization;
    /**
     * 
     * @type {Date}
     * @memberof ExternalIncomingOrder
     */
    validFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExternalIncomingOrder
     */
    validUntil?: Date;
    /**
     * 
     * @type {Array<ManagementexternalOrderService>}
     * @memberof ExternalIncomingOrder
     */
    services?: Array<ManagementexternalOrderService>;
    /**
     * 
     * @type {Date}
     * @memberof ExternalIncomingOrder
     */
    revokedAt?: Date;
}

/**
 * Check if a given object implements the ExternalIncomingOrder interface.
 */
export function instanceOfExternalIncomingOrder(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ExternalIncomingOrderFromJSON(json: any): ExternalIncomingOrder {
    return ExternalIncomingOrderFromJSONTyped(json, false);
}

export function ExternalIncomingOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalIncomingOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reference': !exists(json, 'reference') ? undefined : json['reference'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'delegator': !exists(json, 'delegator') ? undefined : ExternalOrganizationFromJSON(json['delegator']),
        'validFrom': !exists(json, 'valid_from') ? undefined : (new Date(json['valid_from'])),
        'validUntil': !exists(json, 'valid_until') ? undefined : (new Date(json['valid_until'])),
        'services': !exists(json, 'services') ? undefined : ((json['services'] as Array<any>).map(ManagementexternalOrderServiceFromJSON)),
        'revokedAt': !exists(json, 'revoked_at') ? undefined : (new Date(json['revoked_at'])),
    };
}

export function ExternalIncomingOrderToJSON(value?: ExternalIncomingOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reference': value.reference,
        'description': value.description,
        'delegator': ExternalOrganizationToJSON(value.delegator),
        'valid_from': value.validFrom === undefined ? undefined : (value.validFrom.toISOString()),
        'valid_until': value.validUntil === undefined ? undefined : (value.validUntil.toISOString()),
        'services': value.services === undefined ? undefined : ((value.services as Array<any>).map(ManagementexternalOrderServiceToJSON)),
        'revoked_at': value.revokedAt === undefined ? undefined : (value.revokedAt.toISOString()),
    };
}

