/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ManagementAccessGrant,
    ManagementAccessGrantFromJSON,
    ManagementAccessGrantFromJSONTyped,
    ManagementAccessGrantToJSON,
} from './';

/**
 * 
 * @export
 * @interface ManagementListAccessGrantsForServiceResponse
 */
export interface ManagementListAccessGrantsForServiceResponse {
    /**
     * 
     * @type {Array<ManagementAccessGrant>}
     * @memberof ManagementListAccessGrantsForServiceResponse
     */
    accessGrants?: Array<ManagementAccessGrant>;
}

export function ManagementListAccessGrantsForServiceResponseFromJSON(json: any): ManagementListAccessGrantsForServiceResponse {
    return ManagementListAccessGrantsForServiceResponseFromJSONTyped(json, false);
}

export function ManagementListAccessGrantsForServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementListAccessGrantsForServiceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessGrants': !exists(json, 'accessGrants') ? undefined : ((json['accessGrants'] as Array<any>).map(ManagementAccessGrantFromJSON)),
    };
}

export function ManagementListAccessGrantsForServiceResponseToJSON(value?: ManagementListAccessGrantsForServiceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accessGrants': value.accessGrants === undefined ? undefined : ((value.accessGrants as Array<any>).map(ManagementAccessGrantToJSON)),
    };
}


