/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ManagementOrderService,
    ManagementOrderServiceFromJSON,
    ManagementOrderServiceFromJSONTyped,
    ManagementOrderServiceToJSON,
} from './';

/**
 * 
 * @export
 * @interface ManagementUpdateOutgoingOrderRequest
 */
export interface ManagementUpdateOutgoingOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof ManagementUpdateOutgoingOrderRequest
     */
    reference?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagementUpdateOutgoingOrderRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagementUpdateOutgoingOrderRequest
     */
    publicKeyPEM?: string;
    /**
     * 
     * @type {Date}
     * @memberof ManagementUpdateOutgoingOrderRequest
     */
    validFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ManagementUpdateOutgoingOrderRequest
     */
    validUntil?: Date;
    /**
     * 
     * @type {Array<ManagementOrderService>}
     * @memberof ManagementUpdateOutgoingOrderRequest
     */
    services?: Array<ManagementOrderService>;
}

export function ManagementUpdateOutgoingOrderRequestFromJSON(json: any): ManagementUpdateOutgoingOrderRequest {
    return ManagementUpdateOutgoingOrderRequestFromJSONTyped(json, false);
}

export function ManagementUpdateOutgoingOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementUpdateOutgoingOrderRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reference': !exists(json, 'reference') ? undefined : json['reference'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'publicKeyPEM': !exists(json, 'publicKeyPEM') ? undefined : json['publicKeyPEM'],
        'validFrom': !exists(json, 'validFrom') ? undefined : (new Date(json['validFrom'])),
        'validUntil': !exists(json, 'validUntil') ? undefined : (new Date(json['validUntil'])),
        'services': !exists(json, 'services') ? undefined : ((json['services'] as Array<any>).map(ManagementOrderServiceFromJSON)),
    };
}

export function ManagementUpdateOutgoingOrderRequestToJSON(value?: ManagementUpdateOutgoingOrderRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reference': value.reference,
        'description': value.description,
        'publicKeyPEM': value.publicKeyPEM,
        'validFrom': value.validFrom === undefined ? undefined : (value.validFrom.toISOString()),
        'validUntil': value.validUntil === undefined ? undefined : (value.validUntil.toISOString()),
        'services': value.services === undefined ? undefined : ((value.services as Array<any>).map(ManagementOrderServiceToJSON)),
    };
}


