/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ManagementOutgoingAccessRequest } from './ManagementOutgoingAccessRequest';
import {
    ManagementOutgoingAccessRequestFromJSON,
    ManagementOutgoingAccessRequestFromJSONTyped,
    ManagementOutgoingAccessRequestToJSON,
} from './ManagementOutgoingAccessRequest';

/**
 * 
 * @export
 * @interface ManagementRequestAccessToServiceResponse
 */
export interface ManagementRequestAccessToServiceResponse {
    /**
     * 
     * @type {ManagementOutgoingAccessRequest}
     * @memberof ManagementRequestAccessToServiceResponse
     */
    outgoingAccessRequest?: ManagementOutgoingAccessRequest;
}

/**
 * Check if a given object implements the ManagementRequestAccessToServiceResponse interface.
 */
export function instanceOfManagementRequestAccessToServiceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ManagementRequestAccessToServiceResponseFromJSON(json: any): ManagementRequestAccessToServiceResponse {
    return ManagementRequestAccessToServiceResponseFromJSONTyped(json, false);
}

export function ManagementRequestAccessToServiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementRequestAccessToServiceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'outgoingAccessRequest': !exists(json, 'outgoing_access_request') ? undefined : ManagementOutgoingAccessRequestFromJSON(json['outgoing_access_request']),
    };
}

export function ManagementRequestAccessToServiceResponseToJSON(value?: ManagementRequestAccessToServiceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'outgoing_access_request': ManagementOutgoingAccessRequestToJSON(value.outgoingAccessRequest),
    };
}

