/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ExternalOrganization,
    ExternalOrganizationFromJSON,
    ExternalOrganizationFromJSONTyped,
    ExternalOrganizationToJSON,
} from './ExternalOrganization';

/**
 * 
 * @export
 * @interface ManagementexternalOrderService
 */
export interface ManagementexternalOrderService {
    /**
     * 
     * @type {ExternalOrganization}
     * @memberof ManagementexternalOrderService
     */
    organization?: ExternalOrganization;
    /**
     * 
     * @type {string}
     * @memberof ManagementexternalOrderService
     */
    service?: string;
}

export function ManagementexternalOrderServiceFromJSON(json: any): ManagementexternalOrderService {
    return ManagementexternalOrderServiceFromJSONTyped(json, false);
}

export function ManagementexternalOrderServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementexternalOrderService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'organization': !exists(json, 'organization') ? undefined : ExternalOrganizationFromJSON(json['organization']),
        'service': !exists(json, 'service') ? undefined : json['service'],
    };
}

export function ManagementexternalOrderServiceToJSON(value?: ManagementexternalOrderService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'organization': ExternalOrganizationToJSON(value.organization),
        'service': value.service,
    };
}

