/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ManagementDirectoryService,
    ManagementDirectoryServiceFromJSON,
    ManagementDirectoryServiceFromJSONTyped,
    ManagementDirectoryServiceToJSON,
} from './';

/**
 * 
 * @export
 * @interface ManagementDirectoryListServicesResponse
 */
export interface ManagementDirectoryListServicesResponse {
    /**
     * 
     * @type {Array<ManagementDirectoryService>}
     * @memberof ManagementDirectoryListServicesResponse
     */
    services?: Array<ManagementDirectoryService>;
}

export function ManagementDirectoryListServicesResponseFromJSON(json: any): ManagementDirectoryListServicesResponse {
    return ManagementDirectoryListServicesResponseFromJSONTyped(json, false);
}

export function ManagementDirectoryListServicesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementDirectoryListServicesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'services': !exists(json, 'services') ? undefined : ((json['services'] as Array<any>).map(ManagementDirectoryServiceFromJSON)),
    };
}

export function ManagementDirectoryListServicesResponseToJSON(value?: ManagementDirectoryListServicesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'services': value.services === undefined ? undefined : ((value.services as Array<any>).map(ManagementDirectoryServiceToJSON)),
    };
}


