/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManagementOrganization
 */
export interface ManagementOrganization {
    /**
     * 
     * @type {string}
     * @memberof ManagementOrganization
     */
    serialNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagementOrganization
     */
    name?: string;
}

export function ManagementOrganizationFromJSON(json: any): ManagementOrganization {
    return ManagementOrganizationFromJSONTyped(json, false);
}

export function ManagementOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementOrganization {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'serialNumber': !exists(json, 'serial_number') ? undefined : json['serial_number'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function ManagementOrganizationToJSON(value?: ManagementOrganization | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'serial_number': value.serialNumber,
        'name': value.name,
    };
}

