/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ManagementTXLogRecord } from './ManagementTXLogRecord';
import {
    ManagementTXLogRecordFromJSON,
    ManagementTXLogRecordFromJSONTyped,
    ManagementTXLogRecordToJSON,
} from './ManagementTXLogRecord';

/**
 * 
 * @export
 * @interface ManagementTXLogListRecordsResponse
 */
export interface ManagementTXLogListRecordsResponse {
    /**
     * 
     * @type {Array<ManagementTXLogRecord>}
     * @memberof ManagementTXLogListRecordsResponse
     */
    records?: Array<ManagementTXLogRecord>;
}

/**
 * Check if a given object implements the ManagementTXLogListRecordsResponse interface.
 */
export function instanceOfManagementTXLogListRecordsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ManagementTXLogListRecordsResponseFromJSON(json: any): ManagementTXLogListRecordsResponse {
    return ManagementTXLogListRecordsResponseFromJSONTyped(json, false);
}

export function ManagementTXLogListRecordsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagementTXLogListRecordsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'records': !exists(json, 'records') ? undefined : ((json['records'] as Array<any>).map(ManagementTXLogRecordFromJSON)),
    };
}

export function ManagementTXLogListRecordsResponseToJSON(value?: ManagementTXLogListRecordsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'records': value.records === undefined ? undefined : ((value.records as Array<any>).map(ManagementTXLogRecordToJSON)),
    };
}

