/* tslint:disable */
/* eslint-disable */
/**
 * management.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ServiceAuthorizationSettings,
    ServiceAuthorizationSettingsFromJSON,
    ServiceAuthorizationSettingsFromJSONTyped,
    ServiceAuthorizationSettingsToJSON,
} from './';

/**
 * 
 * @export
 * @interface NlxmanagementService
 */
export interface NlxmanagementService {
    /**
     * 
     * @type {string}
     * @memberof NlxmanagementService
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof NlxmanagementService
     */
    endpointURL?: string;
    /**
     * 
     * @type {string}
     * @memberof NlxmanagementService
     */
    documentationURL?: string;
    /**
     * 
     * @type {string}
     * @memberof NlxmanagementService
     */
    apiSpecificationURL?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NlxmanagementService
     */
    internal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NlxmanagementService
     */
    techSupportContact?: string;
    /**
     * 
     * @type {string}
     * @memberof NlxmanagementService
     */
    publicSupportContact?: string;
    /**
     * 
     * @type {ServiceAuthorizationSettings}
     * @memberof NlxmanagementService
     */
    authorizationSettings?: ServiceAuthorizationSettings;
    /**
     * 
     * @type {Array<string>}
     * @memberof NlxmanagementService
     */
    inways?: Array<string>;
}

export function NlxmanagementServiceFromJSON(json: any): NlxmanagementService {
    return NlxmanagementServiceFromJSONTyped(json, false);
}

export function NlxmanagementServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): NlxmanagementService {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'endpointURL': !exists(json, 'endpointURL') ? undefined : json['endpointURL'],
        'documentationURL': !exists(json, 'documentationURL') ? undefined : json['documentationURL'],
        'apiSpecificationURL': !exists(json, 'apiSpecificationURL') ? undefined : json['apiSpecificationURL'],
        'internal': !exists(json, 'internal') ? undefined : json['internal'],
        'techSupportContact': !exists(json, 'techSupportContact') ? undefined : json['techSupportContact'],
        'publicSupportContact': !exists(json, 'publicSupportContact') ? undefined : json['publicSupportContact'],
        'authorizationSettings': !exists(json, 'authorizationSettings') ? undefined : ServiceAuthorizationSettingsFromJSON(json['authorizationSettings']),
        'inways': !exists(json, 'inways') ? undefined : json['inways'],
    };
}

export function NlxmanagementServiceToJSON(value?: NlxmanagementService | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'endpointURL': value.endpointURL,
        'documentationURL': value.documentationURL,
        'apiSpecificationURL': value.apiSpecificationURL,
        'internal': value.internal,
        'techSupportContact': value.techSupportContact,
        'publicSupportContact': value.publicSupportContact,
        'authorizationSettings': ServiceAuthorizationSettingsToJSON(value.authorizationSettings),
        'inways': value.inways,
    };
}


