@startuml
title: Access synchronization mechanism

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox

box "Organization A"
participant "Management API" as managementAPIOrgA
database "Management database" as managementDatabaseOrgA
end box

box "Organization B"
participant "Inway" as inwayOrgB
participant "NLX management" as managementUIOrgB
participant "Management API" as managementAPIOrgB
database "Management database" as managementDatabaseOrgB
end box

loop Run every 1.5 seconds
    managementAPIOrgA -> managementDatabaseOrgA: Get an outgoing access request with the state 'created', 'received' or 'approved'. Prioritize access requests with the state 'created' and least recently updated
    managementAPIOrgA -> managementDatabaseOrgA: Lock access request for 5 minutes
    managementDatabaseOrgA -> managementAPIOrgA: Return outgoing access request
    alt state created
        managementAPIOrgA -> inwayOrgB: Request access
        inwayOrgB -> managementAPIOrgB: Request access
         alt request access succeeds
            managementAPIOrgB -> managementDatabaseOrgB: Get Service
            managementDatabaseOrgB -> managementAPIOrgB: Return service
            alt service exits
                managementAPIOrgB -> managementDatabaseOrgB: Check if an active incoming access request already exists for organization and service
                alt incoming access request exists 
                    managementDatabaseOrgB -> managementAPIOrgB: Return incoming access request
                else no active access request
                    managementAPIOrgB -> managementDatabaseOrgB: Create incoming access request
                end
                managementAPIOrgB -> inwayOrgB: Return access request state and incoming access request ID
                inwayOrgB -> managementAPIOrgA: Return access request state and incoming access request ID
                managementAPIOrgA -> managementDatabaseOrgA: update state and reference ID of outgoing access request
            else 
                managementDatabaseOrgB -> managementAPIOrgB: Error service no longer exists
                managementAPIOrgB -> inwayOrgB: Error service no longer exists
                inwayOrgB -> managementAPIOrgA: Error service no longer exists
                managementAPIOrgA -> managementDatabaseOrgA: Delete outgoing access request for service
            end
        else request access fails
            managementAPIOrgA -> managementDatabaseOrgA: Update state of outgoing access request to failed
        end
    else state received
        managementAPIOrgA -> inwayOrgB: Get access request state
        inwayOrgB -> managementAPIOrgB: Get access request state
        alt get access request state succeeds
            managementAPIOrgB -> managementDatabaseOrgB: Get Service
            managementDatabaseOrgB -> managementAPIOrgB: Return service
            alt service exits
                managementAPIOrgB -> managementDatabaseOrgB: Get incoming access request state (latest access request stored of the organization)
                managementDatabaseOrgB -> managementAPIOrgB: Return incoming access request state
                managementAPIOrgB -> inwayOrgB: Return incoming access request state
                inwayOrgB -> managementAPIOrgA: Return incoming access request state
                managementAPIOrgA -> managementDatabaseOrgB: Update state of the outgoing access request
            else 
                managementDatabaseOrgB -> managementAPIOrgB: Error service no longer exists
                managementAPIOrgB -> inwayOrgB: Error service no longer exists
                inwayOrgB -> managementAPIOrgA: Error service no longer exists
                managementAPIOrgA -> managementDatabaseOrgA: Delete outgoing access request for service
            end
        else get access request state fails 
            managementAPIOrgA -> managementDatabaseOrgA: Update state of outgoing access request to failed
        end
    else state approved
        managementAPIOrgA -> inwayOrgB: Retrieve access proof
        inwayOrgB -> managementAPIOrgB: Retrieve access proof
        alt retrieve access proof succeeds
            managementAPIOrgB -> managementDatabaseOrgB: Get Service
            managementDatabaseOrgB -> managementAPIOrgB: Return service
            alt service exits
                managementAPIOrgB -> managementDatabaseOrgB: Get latest access grant (servicename + organization serialnumber)
                managementDatabaseOrgB -> managementAPIOrgB: Return access grant
                managementAPIOrgB -> inwayOrgB: Return access proof
                inwayOrgB -> managementAPIOrgA: Return access proof
                managementAPIOrgA -> managementDatabaseOrgA: Get access proof
                managementDatabaseOrgA -> managementAPIOrgA: Return access proof
                alt access proof reference ID matches outgoing access request ID
                    alt access proof does exists
                        managementAPIOrgA -> managementDatabaseOrgA: Create access proof
                    end
                    alt access proof revoked
                        managementAPIOrgA -> managementDatabaseOrgA: Revoke access proof
                    end
                end
            else service no longer exists
                managementDatabaseOrgB -> managementAPIOrgB: Error service no longer exists
                managementAPIOrgB -> inwayOrgB: Error service no longer exists
                inwayOrgB -> managementAPIOrgA: Error service no longer exists
                managementAPIOrgA -> managementDatabaseOrgA: Delete outgoing access request for service
            end
        else retrieve access proof fails
            managementAPIOrgA -> managementDatabaseOrgA: Update state of outgoing access request to failed
        end
    end
    managementAPIOrgA -> managementDatabaseOrgA: Remove lock from outgoing access request
end
@enduml