@startuml
title: Consume a service offered by a delegate

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox

box "API Consumer"
actor "Client" as clientConsumer
participant "Outway" as outwayConsumer
end box


box "Saas Organization"
participant "Inway" as inwaySaasOrganization
participant "Management API" as managementAPISaasOrganization
participant "Management Database" as managementDatabaseSaasOrganization
participant "Service" as serviceSaasOrganization
end box

box "Municipality"
participant "Inway" as inwayMunicipality
participant "Management API" as managementAPIMunicipality
end box

inwaySaasOrganization -> inwayMunicipality: get claim for publishing service
inwayMunicipality -> managementAPIMunicipality: get publication-claim
managementAPIMunicipality -> inwayMunicipality: return publication-claim
inwayMunicipality -> inwaySaasOrganization: return publication-claim
inwaySaasOrganization -> inwaySaasOrganization: store publication-claim in memory
inwaySaasOrganization -> managementAPISaasOrganization: get access grants
managementAPISaasOrganization -> managementDatabaseSaasOrganization: get access grants
managementDatabaseSaasOrganization -> managementAPISaasOrganization: return access grants
managementAPISaasOrganization -> inwaySaasOrganization: store access grants in memory

clientConsumer -> outwayConsumer: call service
outwayConsumer -> inwaySaasOrganization: get publication-claim stating that the organization is allowed to  publish the service
inwaySaasOrganization -> outwayConsumer: return publication-claim
outwayConsumer -> outwayConsumer: verify publication-claim
outwayConsumer -> outwayConsumer: store publication-claim in memory
outwayConsumer -> inwaySaasOrganization: call service
inwaySaasOrganization -> inwaySaasOrganization: validate consumer has an access grant
inwaySaasOrganization -> serviceSaasOrganization: call service

@enduml
