@startuml
title: Offer a service on behalf of a delegator

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox

box "Saas Organization"
actor "Administrator" as administratorSaasOrganization
participant "Management UI" as managementUISaasOrganization
participant "Inway" as inwaySaasOrganization
participant "Management API" as managementAPISaasOrganization
participant "Management database" as managementDatabaseSaasOrganization
end box

box "Municipality"
participant "Inway" as inwayMunicipality
participant "Management API" as managementAPIMunicipality
database "Management database" as managementDatabaseMunicipality
end box

box "Directory"
participant "Directory API" as directoryAPI
participant "Directory DB" as directoryDatabase
end box

administratorSaasOrganization -> managementUISaasOrganization: add service using an order
managementUISaasOrganization -> managementAPISaasOrganization: add service using an order
managementAPISaasOrganization -> managementAPISaasOrganization: does service name match with service name in order
managementAPISaasOrganization -> managementDatabaseSaasOrganization: store service

inwaySaasOrganization -> managementAPISaasOrganization: get config
managementAPISaasOrganization -> managementDatabaseSaasOrganization: get service and orders for inway
managementDatabaseSaasOrganization -> managementAPISaasOrganization: return services and orders
managementAPISaasOrganization -> inwaySaasOrganization: return config

inwaySaasOrganization -> inwayMunicipality: get claim for publicing the service
inwayMunicipality -> managementAPIMunicipality: get claim for publicing the service
managementAPIMunicipality -> managementDatabaseMunicipality: get order
managementDatabaseMunicipality -> managementAPIMunicipality: return order
managementAPIMunicipality -> managementAPIMunicipality: validate order
managementAPIMunicipality -> managementAPIMunicipality: create claim
managementAPIMunicipality -> inwayMunicipality: return claim
inwayMunicipality -> inwaySaasOrganization: return claim
inwaySaasOrganization -> inwaySaasOrganization: store claim in memory
inwaySaasOrganization -> directoryAPI: register service with claim
directoryAPI -> inwayMunicipality: get public key of the municipality
inwayMunicipality -> directoryAPI: return public key
directoryAPI -> directoryAPI: validate claim
directoryAPI -> directoryDatabase: register service

@enduml
