@startuml
title: Request access to a service

skinparam sequenceBoxBorderColor #transparent
skinparam boxPadding 50
hide footbox

box "Organization A"
actor "User" as userOrgA
participant "NLX Management" as managementUIOrgA
participant "Management API" as managementAPIOrgA
database "Management database" as managementDatabaseOrgA
end box

box "Organization B"
actor "User" as userOrgB
participant "Inway" as inwayOrgB
participant "NLX Management" as managementUIOrgB
participant "Management API" as managementAPIOrgB
database "Management database" as managementDatabaseOrgB
end box

userOrgA -> managementUIOrgA: Request access to service X
managementUIOrgA -> managementAPIOrgA: Request access to service X
managementAPIOrgA -> inwayOrgB: Request access
        inwayOrgB -> managementAPIOrgB: Request access
        managementAPIOrgB -> managementDatabaseOrgB: Check if an active incoming access request already exists
        alt incoming access request exists
        managementDatabaseOrgB -> managementAPIOrgB: Return incoming access request
        else no active access request
        managementAPIOrgB -> managementDatabaseOrgB: Create incoming access request
        end
        managementAPIOrgB -> inwayOrgB: Access request received
        inwayOrgB -> managementAPIOrgA: Access request received
managementAPIOrgA -> managementDatabaseOrgA: Store outgoing access request with state 'received'
managementAPIOrgA -> managementUIOrgA: Access request send
managementUIOrgA -> userOrgA: Show message 'access request send'

@enduml
