// Copyright © VNG Realisatie 2020
// Licensed under the EUPL
//
export { ReactComponent as IconArrowLeftRight } from './arrow-left-right.svg'
export { ReactComponent as IconBin } from './bin.svg'
export { ReactComponent as IconCheck } from './check.svg'
export { ReactComponent as IconChevron } from './chevron.svg'
export { ReactComponent as IconDirectory } from './directory.svg'
export { ReactComponent as IconExternalLink } from './external-link.svg'
export { ReactComponent as IconHidden } from './hidden.svg'
export { ReactComponent as IconInway } from './inway.svg'
export { ReactComponent as IconKey } from './key.svg'
export { ReactComponent as IconOrganization } from './organization.svg'
export { ReactComponent as IconPencil } from './pencil.svg'
export { ReactComponent as IconPlus } from './plus.svg'
export { ReactComponent as IconRedo } from './redo.svg'
export { ReactComponent as IconServices } from './services.svg'
export { ReactComponent as IconStateDegraded } from './state-degraded.svg'
export { ReactComponent as IconStateDown } from './state-down.svg'
export { ReactComponent as IconStateUnknown } from './state-unknown.svg'
export { ReactComponent as IconStateUp } from './state-up.svg'
export { ReactComponent as IconVisible } from './visible.svg'
export { ReactComponent as IconWarningCircle } from './error-warning.svg'
export { ReactComponent as IconWarningCircleFill } from './error-warning-fill.svg'
