// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package queries

import (
	"fmt"
	"time"

	"github.com/tabbed/pqtype"
)

type TransactionlogDirection string

const (
	TransactionlogDirectionIn  TransactionlogDirection = "in"
	TransactionlogDirectionOut TransactionlogDirection = "out"
)

func (e *TransactionlogDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionlogDirection(s)
	case string:
		*e = TransactionlogDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionlogDirection: %T", src)
	}
	return nil
}

type TransactionlogDatasubject struct {
	ID       int64
	RecordID int64
	Key      string
	Value    string
}

type TransactionlogRecord struct {
	ID               int64
	Direction        TransactionlogDirection
	Created          time.Time
	SrcOrganization  string
	DestOrganization string
	ServiceName      string
	LogrecordID      string
	Data             pqtype.NullRawMessage
	Delegator        string
	OrderReference   string
}
