DROP ROLE IF EXISTS "nlx-txlog-api";
CREATE ROLE "nlx-txlog-api";
ALTER ROLE "nlx-txlog-api" WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'md59394173faf221850af2bcbd99b3ddd9a';

DROP ROLE IF EXISTS "nlx-txlog-writer";
CREATE ROLE "nlx-txlog-writer";
ALTER ROLE "nlx-txlog-writer" WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'md516e6ab91b15636484b216cb83016c983';
